# Generated by Django 4.2.14 on 2024-07-12 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_result_school_name_alter_result_whatsapp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='area',
        ),
    ]
